version: '3.8'

services:
  ollama:
    image: ollama/ollama:0.7.1
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: >
      /bin/sh -c "
        ollama serve & 
        sleep 5 && 
        ollama run mistral && 
        wait
      "
    environment:
      - OLLAMA_MODELS=mistral
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  vectordb:
    image: qdrant/qdrant
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"     # HTTP API
      - "6334:6334"     # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data

  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    restart: always
    ports:
      - "4000:8080"
    volumes:
      - ./searXNG/settings.yml:/etc/searxng/settings.yml

  comfyui-boot:
      image: yanwk/comfyui-boot:cu124-slim
      stdin_open: true
      tty: true
      container_name: comfyui-cu124
      ports:
          - 8288:8188
      volumes:
          - './vision/ComfyUIdocker:/root'
      deploy:
          resources:
              reservations:
                  devices:
                      - driver: nvidia
                        count: all
                        capabilities:
                            - gpu

volumes:
  ollama_data:
  qdrant_storage:
  open-webui: