version: '3.8'

services:
  ollama:
    image: ollama/ollama:0.7.1
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: >
      /bin/sh -c "
        ollama serve & 
        sleep 5 && 
        ollama run mistral && 
        wait
      "
    environment:
      - OLLAMA_MODELS=mistral
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  vectordb:
    image: qdrant/qdrant
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"     # HTTP API
      - "6334:6334"     # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  ollama_data:
  qdrant_storage: