[project]
name = "synapserag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "qdrant-client>=1.14.2",
    "requests>=2.32.3",
    "sentence-transformers>=4.1.0",
]
